google_analytics_id: UA-29540572-1

repository: https://github.com/TEELAB-X/TEELAB

timezone: Asia/Shanghai

name: TEELAB
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: Official Website
url: http://teelab.net/
contact: contact[at]teelab[dot]net
github: https://github.com/TEELAB-X

logo: /img/Avatar.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor